### PR TITLE
Upgrade to ownCloud 9.0 and use new YunoHost facilities

### PR DESCRIPTION
**Pull request by jeromelebleu**
Tests are welcome, especially the upgrade from the official version! :) Thanks in advance.

_As there is a lot of changes, I'm not sure if we have to worry about merging it instead of using a new clean branch._

### CODE REVIEW

**Comment by Psycojoker** [comment]
Do we need yunohost 2.2 or 2.4 to test that?

**Comment by jeromelebleu** [comment]
It requires the new 2.4 YunoHost version.

**Comment by raf64flo** [comment]
Hello, any advice on how to upgrade from 2.2 to 2.4? I did not find any facilities neither instructions.

**Comment by jeromelebleu** [comment]
@raf64flo, sorry about that, it's currently being drafted and should come soon...

**Comment by raf64flo** [comment]
Do not forgive, it'll be published when it will be ready. Thanks for your fast answer. o/

I keep in touch.

**Comment by jeromelebleu** [comment]
Done [here](https://github.com/YunoHost-Apps/owncloud_ynh), with cleaned history to not have to download all the previous archives and source code.

@raf64flo, the instructions to upgrade from 2.2 to 2.4 are still not published... Hope it will come soon...

**Pull request closed without merging**
